### ISSUE TITLE
Investigate non-shiny hunts.

### ISSUE THREAD

**Issue by Mysticial** [Mysticial/Pokemon-Automation-SwSh-Arduino-Scripts#11]
Which of these are possible and can we do them?

- Poipole and Cosmog: Stat hunting
- Keldeo: Stat and mark hunting
- Galar Birds: Stat and mark hunting
- Calyrex: Stat hunting
- Regis: Stat hunting

**Comment by Mysticial** [comment]
Type: Null, Cosmog, and Poipole will be available in the next release.

**Comment by Mysticial** [comment]
https://github.com/PokemonAutomation/SwSh-Arduino/issues/15
https://github.com/PokemonAutomation/SwSh-Arduino/issues/14

**Comment by pifopi** [comment]
#21
